// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1pQroqzvrcxqm9yvhA3TwHqCQ86S56qI',
    appId: '1:282231037841:web:29edaa3e2de3d4072b8430',
    messagingSenderId: '282231037841',
    projectId: 'fir-crud-788ba',
    authDomain: 'fir-crud-788ba.firebaseapp.com',
    storageBucket: 'fir-crud-788ba.firebasestorage.app',
    measurementId: 'G-6WZPDJ0JGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_ZyxfKjC6t8YzUg-jLXegCRN5s0P5jQ',
    appId: '1:282231037841:android:a80bf68a076302f12b8430',
    messagingSenderId: '282231037841',
    projectId: 'fir-crud-788ba',
    storageBucket: 'fir-crud-788ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH6MilSb1-OhNSWxz7nuNpcIQzvv6a-ww',
    appId: '1:282231037841:ios:18d2e560f1e38c3d2b8430',
    messagingSenderId: '282231037841',
    projectId: 'fir-crud-788ba',
    storageBucket: 'fir-crud-788ba.firebasestorage.app',
    iosBundleId: 'com.example.crudExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH6MilSb1-OhNSWxz7nuNpcIQzvv6a-ww',
    appId: '1:282231037841:ios:18d2e560f1e38c3d2b8430',
    messagingSenderId: '282231037841',
    projectId: 'fir-crud-788ba',
    storageBucket: 'fir-crud-788ba.firebasestorage.app',
    iosBundleId: 'com.example.crudExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1pQroqzvrcxqm9yvhA3TwHqCQ86S56qI',
    appId: '1:282231037841:web:316463133480213f2b8430',
    messagingSenderId: '282231037841',
    projectId: 'fir-crud-788ba',
    authDomain: 'fir-crud-788ba.firebaseapp.com',
    storageBucket: 'fir-crud-788ba.firebasestorage.app',
    measurementId: 'G-5LW55C8CYF',
  );
}
